"""
逐个语言：读 app_strings_en.dart → 机翻 → 直接写回 app_strings_<lang>.dart。
不经过 JSON。英语 / 简中 / 繁中不覆盖（请手改 app_strings_zh*.dart）。

用法：
  python tool/translate_dart_locales.py              # 西葡德法日韩 六个文件依次翻译
  python tool/translate_dart_locales.py --lang ja ko  # 只日语、韩语
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tool"))

from l10n_parse import parse_app_strings_dart  # noqa: E402
from translate_l10n_json import translate_map_batched  # noqa: E402

L10N = ROOT / "lib" / "l10n"
EN_FILE = L10N / "app_strings_en.dart"

# 文件名、Dart 变量名、Google Translate 目标码（与 translate_l10n_json 一致）
LOCALES: list[tuple[str, str, str]] = [
    ("app_strings_es.dart", "kAppStringsEs", "es"),
    ("app_strings_pt_br.dart", "kAppStringsPtBr", "pt"),
    ("app_strings_de.dart", "kAppStringsDe", "de"),
    ("app_strings_fr.dart", "kAppStringsFr", "fr"),
    ("app_strings_ja.dart", "kAppStringsJa", "ja"),
    ("app_strings_ko.dart", "kAppStringsKo", "ko"),
]


def dart_quote(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def write_dart(path: Path, var_name: str, m: dict[str, str]) -> None:
    lines = [
        "// Generated by tool/translate_dart_locales.py — machine translation from English.",
        "",
        "const Map<String, String> " + var_name + " = {",
    ]
    for k in sorted(m.keys()):
        lines.append(f"  {dart_quote(k)}: {dart_quote(m[k])},")
    lines.append("};")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--lang",
        nargs="*",
        help="只翻译这些 Google 码，例如: ja ko fr（默认全部六种）",
    )
    args = ap.parse_args()
    filter_codes = set(args.lang) if args.lang else None

    en = parse_app_strings_dart(EN_FILE)
    print(f"Loaded {len(en)} keys from {EN_FILE.relative_to(ROOT)}", flush=True)

    for fname, var, gcode in LOCALES:
        if filter_codes is not None and gcode not in filter_codes:
            continue
        out = L10N / fname
        print(f"\n>>> [{fname}] 目标语言码: {gcode}", flush=True)
        m = translate_map_batched(en, gcode)
        write_dart(out, var, m)
        print(f"    已写入 {out.relative_to(ROOT)} ({len(m)} keys)", flush=True)

    print("\n完成。简中/繁中请继续手改 app_strings_zh.dart / app_strings_zh_hant.dart。", flush=True)


if __name__ == "__main__":
    main()
