"""Generate lib/l10n/app_strings_*.dart from app_strings_*.dart + optional JSON overlays."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tool"))
from l10n_parse import parse_app_strings_dart  # noqa: E402

OUT = ROOT / "lib" / "l10n"
ASSETS = ROOT / "assets" / "l10n"


def dart_quote(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def write_strings_file(path: Path, var_name: str, m: dict[str, str]) -> None:
    lines = [
        "// Generated by tool/export_app_strings_dart.py — one language per file.",
        "",
        "const Map<String, String> " + var_name + " = {",
    ]
    for k in sorted(m.keys()):
        lines.append(f"  {dart_quote(k)}: {dart_quote(m[k])},")
    lines.append("};")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def load_json(path: Path) -> dict[str, str] | None:
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None
    return {str(k): str(v) for k, v in data.items() if isinstance(v, str)}


def merge_with_en(en: dict[str, str], overlay: dict[str, str] | None) -> dict[str, str]:
    out = dict(en)
    if overlay:
        out.update(overlay)
    return out


def main() -> None:
    en = parse_app_strings_dart(OUT / "app_strings_en.dart")
    zh = merge_with_en(en, parse_app_strings_dart(OUT / "app_strings_zh.dart"))
    zh_hant = merge_with_en(en, parse_app_strings_dart(OUT / "app_strings_zh_hant.dart"))

    # Overlay JSON translations on English for any missing keys
    es = merge_with_en(en, load_json(ASSETS / "es.json"))
    pt_br = merge_with_en(en, load_json(ASSETS / "pt_BR.json"))
    de = merge_with_en(en, load_json(ASSETS / "de.json"))
    fr = merge_with_en(en, load_json(ASSETS / "fr.json"))
    ja = merge_with_en(en, load_json(ASSETS / "ja.json"))
    ko = merge_with_en(en, load_json(ASSETS / "ko.json"))

    files: list[tuple[str, str, dict[str, str]]] = [
        ("app_strings_en.dart", "kAppStringsEn", en),
        ("app_strings_zh.dart", "kAppStringsZh", zh),
        ("app_strings_zh_hant.dart", "kAppStringsZhHant", zh_hant),
        ("app_strings_es.dart", "kAppStringsEs", es),
        ("app_strings_pt_br.dart", "kAppStringsPtBr", pt_br),
        ("app_strings_de.dart", "kAppStringsDe", de),
        ("app_strings_fr.dart", "kAppStringsFr", fr),
        ("app_strings_ja.dart", "kAppStringsJa", ja),
        ("app_strings_ko.dart", "kAppStringsKo", ko),
    ]

    for filename, var, data in files:
        out_path = OUT / filename
        write_strings_file(out_path, var, data)
        n_overlay = sum(1 for k, v in data.items() if k in en and v != en[k])
        print(f"  {out_path.relative_to(ROOT)}  {len(data)} keys  (differs from en: ~{n_overlay})")

    print("Done.")


if __name__ == "__main__":
    main()
